import os
import io
import zipfile
from typing import Dict, List, Any
from backend.app.models.schemas import Application, Gene

class ExportEngine:
    @staticmethod
    def generate_project_files(app: Application, genes: List[Gene]) -> Dict[str, str]:
        """Compiles standard folder templates representing the generated evolved application code."""
        files = {}
        
        # README.md
        files["README.md"] = f"""# Evolved: {app.name}

Tagline: {app.tagline}
Language: {app.language}
Framework: {app.framework}

Evolved and generated by the **Universal Application Genome (UAG)** research platform.

## Architecture Blueprints
This codebase represents a synthesized architecture. It merges patterns found in:
- Component structures
- Isolated database schemas
- Streamlined router API endpoints

## Genes Incorporated
{chr(10).join([f"- **{g.name}** ({g.gene_type}): {g.description}" for g in genes])}

## Development
To run this application locally:
1. Initialize virtual environment: `python -m venv .venv`
2. Install requirements: `pip install fastapi uvicorn sqlmodel`
3. Run: `uvicorn main:app --reload`
"""

        # main.py (FastAPI application)
        routers_import = ""
        routers_setup = ""
        routes_content = ""
        
        for g in genes:
            clean_name = g.name.lower().replace(" ", "_").replace("&", "and")
            if "auth" in clean_name:
                routes_content += """
@app.post("/api/auth/login")
async def login(credentials: dict):
    # Evolved Authentication Logic
    return {"token": "session_token_xyz123", "status": "authenticated"}

@app.get("/api/auth/profile")
async def profile():
    return {"id": "user_id_001", "role": "admin"}
"""
            elif "payment" in clean_name or "transactional" in clean_name:
                routes_content += """
@app.post("/api/billing/checkout")
async def checkout(order: dict):
    # Evolved Payment Gene
    return {"invoice_id": "inv_9988", "url": "https://gateway.checkout/pay", "status": "pending"}
"""
            elif "sync" in clean_name or "stream" in clean_name:
                routes_content += """
@app.get("/api/sync/events")
async def event_stream():
    # Websocket / sync polling mock
    return {"events": [{"id": 1, "topic": "updates", "content": "Genome updated"}]}
"""
            else:
                routes_content += f"""
@app.get("/api/features/{clean_name}")
async def get_{clean_name}():
    # Service handler for {g.name}
    return {{"gene_type": "{g.gene_type}", "status": "active"}}
"""

        files["main.py"] = f"""# Evolved application entry-point
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from sqlmodel import SQLModel, create_engine

app = FastAPI(title={repr(app.name)}, version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
async def root():
    return {{"message": "Welcome to {app.name} evolved genome API"}}
{routes_content}
"""

        # Database Schema: schema.sql
        tables_content = ""
        for g in genes:
            if "persistence" in g.name.lower() or "schema" in g.name.lower():
                tables_content += """
CREATE TABLE users (
    id VARCHAR(50) PRIMARY KEY,
    email VARCHAR(100) UNIQUE,
    hashed_password VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""
            elif "payment" in g.name.lower():
                tables_content += """
CREATE TABLE ledger_transactions (
    id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50),
    amount NUMERIC(10, 2),
    currency VARCHAR(3),
    gateway_status VARCHAR(20)
);
"""
        if not tables_content:
            tables_content = """
CREATE TABLE application_nodes (
    id VARCHAR(50) PRIMARY KEY,
    node_name VARCHAR(100),
    data_payload TEXT
);
"""
        files["schema.sql"] = f"""-- Database tables generated from {app.name} DNA
{tables_content}
"""

        # Next.js Component: Page.tsx
        files["Page.tsx"] = f"""// React/Next.js frontend view evolved for {app.name}
import React from 'react';

export default function EvolvedAppDashboard() {{
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8 font-sans">
      <header className="border-b border-slate-800 pb-4 mb-8">
        <h1 className="text-3xl font-extrabold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-indigo-500">
          {app.name}
        </h1>
        <p className="text-slate-400 mt-2 text-sm">{app.tagline}</p>
      </header>
      
      <main className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <section className="bg-slate-900 border border-slate-800 rounded-lg p-6">
          <h2 className="text-xl font-bold mb-4 text-cyan-300">Extracted Genes Active</h2>
          <ul className="space-y-3">
            {chr(10).join([f'            <li className="text-xs border-b border-slate-800 pb-2"><strong className="text-indigo-400">{g.name}</strong> - {g.gene_type}</li>' for g in genes])}
          </ul>
        </section>
        
        <section className="bg-slate-900 border border-slate-800 rounded-lg p-6">
          <h2 className="text-xl font-bold mb-4 text-indigo-300">Interact and Run</h2>
          <button className="bg-cyan-500 hover:bg-cyan-600 text-slate-950 font-bold px-4 py-2 rounded text-sm transition">
            Trigger Recombination Flow
          </button>
        </section>
      </main>
    </div>
  );
}}
"""
        return files

    @classmethod
    def compile_zip_archive(cls, app: Application, genes: List[Gene]) -> bytes:
        """Returns a binary ZIP byte-stream containing the generated code files."""
        files = cls.generate_project_files(app, genes)
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
            for name, content in files.items():
                zip_file.writestr(name, content)
        return zip_buffer.getvalue()
